GET http://localhost:3000/home
###
POST http://localhost:3000/auth/login

###

POST http://localhost:3000/auth/register
Content-Type: application/json


{
    
    "email":"G.EMAYE089879@gmail.com",
    "password": "23458"
}

###

POST http://localhost:3000/auth/refresh-token

###
DELETE http://localhost:3000/auth/logout
